server:
  port: 8008

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 3
      permittedNumberOfCallsInHalfOpenState: 2
      waitDurationInOpenState: 10s # second
      failureRateThreshold: 50
      registerHealthIndicator: false
    testServer:
      baseConfig: default # 설정을 override 할 수 있다.
      slidingWindowSize: 100




management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,conditions, metrics, threaddump, heapdump
#        exclude: